apiVersion: v1
kind: Pod
metadata:
  name: fio-benchmark
spec:
  containers:
    - image: quay.io/dystewar/fio-openshift-storage-performance:latest
      command:
        - sleep
        - "inf"
      name: benchmarking
      volumeMounts:
        - mountPath: /target/pv
          name: target-pv
  volumes:
    - name: target-pv
      persistentVolumeClaim:
        claimName: target-pv