apiVersion: v1
kind: Pod
metadata:
  name: fio-benchmark
spec:
  containers:
    - image: quay.io/dystewar/fio-openshift-storage-performance:latest
      name: benchmarking
      volumeMounts:
        - mountPath: /tmp/
          name: results
  volumes:
    - name: results
      persistentVolumeClaim:
        claimName: fio-results