apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-disk
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: quay.io/dystewar/fio-openshift-storage-performance:latest
          imagePullPolicy: IfNotPresent
          name: kubestr-fio-benchmark-disk
          command: ["bash"]
          args: 
            - /scripts/test.sh
            - cp * -r /results/disk
          workingDir: /target/disk
          volumeMounts:
            - mountPath: /target/disk
              name: target-disk
            - mountPath: /results
              name: results
            - mountPath: /scripts
              name: kubestr-scripts
            - mountPath: /fio-jobs
              name: fio-jobs
      volumes:
        - name: target-disk
          emptyDir: {}
        - name: results
          persistentVolumeClaim:
            claimName: fio-results
        - name: kubestr-scripts
          configMap:
            name: run-benchmark
        - name: fio-jobs
          configMap: 
            name: fio-jobs
