apiVersion: v1
kind: Pod
metadata:
  name: benchmark-results
spec:
  containers:
    - image: quay.io/dystewar/fio-openshift-storage-performance:latest
      command:
        - sh  
        - /scripts/test.sh
        - "/pv/result"
        - /scripts/test.sh
        - "/disk/result"
        - sleep
        - "inf"
      name: benchmark-results
      volumeMounts:
        - mountPath: /pv/result
          name: fio-results-pv
        - mountPath: /disk/result
          name: fio-results-disk
        - mountPath: /scripts
          name: kubestr-scripts
        - mountPath: /fio-jobs
          name: fio-jobs
  volumes:
    - name: fio-results-pv
      persistentVolumeClaim:
        claimName: benchmark-target-pv
    - name: fio-results-disk
      emptyDir: {}
    - name: kubestr-scripts
      configMap:
        name: run-benchmark
    - name: fio-jobs
      configMap: 
        name: fio-jobs